In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('salaries.csv')
df

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

# Seperating target and other variables

In [3]:
X = df.drop('salary_more_then_100k',axis=1)
X

company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [5]:
y = df.salary_more_then_100k
y

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

### Now we will do label encoding i.e (One Hot Encoding) to convert our string variables into binary form

In [7]:
from sklearn.preprocessing import LabelEncoder

### Making seperate objects for each column

In [8]:
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()


In [9]:
### Now converting all these col objects into one hot coding i.e binary form by making seperate col for each object

In [10]:
X['company_n']=le_company.fit_transform(X['company'])
X['job_n']=le_company.fit_transform(X['job'])
X['degree_n']=le_company.fit_transform(X['degree'])
X


company                  job     degree  company_n  job_n  degree_n
0       google      sales executive  bachelors          2      2         0
1       google      sales executive    masters          2      2         1
2       google     business manager  bachelors          2      0         0
3       google     business manager    masters          2      0         1
4       google  computer programmer  bachelors          2      1         0
5       google  computer programmer    masters          2      1         1
6   abc pharma      sales executive    masters          0      2         1
7   abc pharma  computer programmer  bachelors          0      1         0
8   abc pharma     business manager  bachelors          0      0         0
9   abc pharma     business manager    masters          0      0         1
10    facebook      sales executive  bachelors          1      2         0
11    facebook      sales executive    masters          1      2         1
12    facebook     business manager  bachelors          1      0         0
13    facebook     business manager    masters          1      0         1
14    facebook  computer programmer  bachelors          1      1         0
15    facebook  computer programmer    masters          1      1         1

In [11]:
# dropping string variable cols

In [12]:
X_n = X.drop(['company','job','degree'],axis=1)
X_n

company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [13]:
y

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [17]:
#First do train test split

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_n_train,X_n_test,y_train,y_test = train_test_split(X_n,y,test_size=0.5)

In [20]:
len(X_n_train)

8

In [21]:
len(X_n_test)

8

### Lets do modelling now

In [22]:
from sklearn import tree

In [23]:
model = tree.DecisionTreeClassifier()
model

DecisionTreeClassifier()

In [25]:
model.fit(X_n_train,y_train)

DecisionTreeClassifier()

In [26]:
model.score(X_n_test,y_test)

0.5

### Q: Is the person having masters degree and being computer programmer in Google has salary above 100k or not?

In [27]:
model.predict([[2,1,1]])

C:\Program Files\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

### Q: Is the person having bachelors degree and being business manager in abc pharma has salary above 100k or not?

In [28]:
model.predict([[0,0,0]])

C:\Program Files\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [29]:
model.predict([[1,2,1]])

C:\Program Files\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)